models:
  phi3-mini-4k-instruct:
    path: "/Users/enikey87/llm/phi3-mini-4k-instruct-q4.gguf"
    name: "phi3-mini-4k-instruct"
    parameters:
      temperature: 0.7
      top_p: 0.9
      max_tokens: 2048
server:
  host: "0.0.0.0"
  port: 11434 